const $=s=>document.querySelector(s);
const SUPABASE_URL='https://ghaxikrkosdeelqhfice.supabase.co',KEY='sb_publishable_N_vKWdSfxtnZVGsStl2YGQ_uxdoU3Wb';
const db=supabase.createClient(SUPABASE_URL,KEY),names=['KD','KP','KF','KR','KT','KA','KW','KK','KO','KB'];
const freshLine=name=>({name,stage:'idle',color:'',bottle:'',prePieces:10000,bag1:1,bag2:1,extraRequested:false,extraLoaded:false,extraAssignedTo:'',assignedTo:'',remainingPieces:null,ctDecision:'',cleanConfirmed:false,nextBottle:'',activity:[]});
const initial=()=>({bottles:[],bottleColors:{},lines:Object.fromEntries(names.map(n=>[n,freshLine(n)]))});
let session=null,profile=null,appState=initial(),selected='KD',saving=false,loading=false,lastRemoteUpdated='';
const labels={idle:'Nessuna richiesta',pre:'Pre-raclage',progress:'In corso','waiting-raclage':'In attesa raclage',raclage:'Raclage','waiting-ct':'In attesa CT','raclage-ok':'Raclage OK',unload:'Scarico linea',finished:'Finito'};
const cls=s=>s==='pre'?'pre':s==='progress'?'progress':s==='unload'?'unload':s==='finished'?'finished':['waiting-raclage','raclage','waiting-ct','raclage-ok'].includes(s)?'raclage':'';
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const now=()=>new Date().toISOString(),showTime=i=>new Date(i).toLocaleString('it-IT',{hour:'2-digit',minute:'2-digit',day:'2-digit',month:'2-digit'});
const actor=()=>profile?.display_name||profile?.email||'Utente',isCT=()=>['ct','admin'].includes(profile?.role),isAdmin=()=>profile?.role==='admin';
function toast(t,e=false){const x=$('#toast');x.textContent=t;x.style.background=e?'#991b1b':'#172033';x.style.display='block';setTimeout(()=>x.style.display='none',2600)}
function event(l,text){l.activity.unshift({text,actor:actor(),at:now()});l.activity=l.activity.slice(0,100)}
function normalize(s){s.bottles=s.bottles||[];s.bottleColors=s.bottleColors||{};for(const n of names)s.lines[n]={...freshLine(n),...(s.lines?.[n]||{})};return s}
async function signIn(){const email=$('#loginEmail').value.trim(),display_name=$('#loginName').value.trim();if(!email)return toast('Inserisci la tua e-mail',true);const {error}=await db.auth.signInWithOtp({email,options:{data:{display_name},emailRedirectTo:location.origin+location.pathname}});if(error)return toast(error.message,true);$('#access').innerHTML='<h2>Controlla la tua e-mail</h2><p>Apri il link ricevuto per entrare nell’app.</p>'}
async function signOut(){await db.auth.signOut();location.reload()}
async function getProfile(){if(!session)return null;const {data,error}=await db.from('profiles').select('*').eq('id',session.user.id).single();if(error)throw error;return data}
function accessScreen(){
 $('#app').hidden=true;$('#identity').innerHTML='';
 if(!session){$('#access').innerHTML='<h2>Accesso Reparto Live</h2><p>Entra con la tua e-mail. I nuovi utenti devono essere approvati dall’amministratore.</p><label class="field">Nome e cognome<input id="loginName" autocomplete="name"></label><label class="field">E-mail<input id="loginEmail" type="email" autocomplete="email"></label><button class="primary" id="login">Invia link di accesso</button>';$('#login').onclick=signIn;return}
 const blocked=profile?.status==='blocked';$('#access').innerHTML=`<h2>${blocked?'Accesso bloccato':'In attesa di approvazione'}</h2><p>${blocked?'L’amministratore ha bloccato questo accesso. Non puoi rientrare senza una nuova approvazione.':'La richiesta è arrivata. L’amministratore deve approvarla prima di mostrare i dati del reparto.'}</p><button id="logout">Esci</button>`;$('#logout').onclick=signOut
}
async function save(){saving=true;try{const stamp=now();const {error}=await db.from('shared_state').update({payload:appState,updated_at:stamp}).eq('id',1);if(error)throw error;lastRemoteUpdated=stamp}catch(e){toast(e.message,true)}finally{saving=false}}
async function loadRemote(){if(saving||loading||profile?.status!=='approved')return;loading=true;try{const {data,error}=await db.from('shared_state').select('payload,updated_at').eq('id',1).single();if(error)throw error;if(data.updated_at!==lastRemoteUpdated){appState=normalize(data.payload||initial());lastRemoteUpdated=data.updated_at;render()}}catch(e){toast('Sincronizzazione non disponibile',true)}finally{loading=false}}
async function act(type,x={}){let l=appState.lines[selected];try{
 if(type==='undo'){if(!l.undo)throw Error('Non c’è un’azione da annullare');const before=l.undo;appState.lines[selected]={...before,undo:null};l=appState.lines[selected];event(l,'Ultima azione annullata');await save();render();return}
 l.undo=JSON.parse(JSON.stringify({...l,undo:null}));
 if(['save-pre','call-raclage','ct-decision','set-stage'].includes(type)&&!isCT())throw Error('Questa azione è riservata al CT');
 if(type==='set-stage'){l.stage=x.stage;event(l,`Stato corretto manualmente: ${labels[x.stage]}`)}
 else if(type==='save-pre'){l.bottle=x.bottle.trim();if(!l.bottle)throw Error('Inserisci il codice flacone');l.color=(appState.bottleColors[l.bottle]||'').trim();if(!l.color)throw Error('Associa prima un colore al codice');l.prePieces=Math.max(0,Number(x.prePieces||0));l.extraRequested=x.extraRequested;l.extraLoaded=false;l.extraAssignedTo='';l.assignedTo='';l.stage='pre';if(!appState.bottles.includes(l.bottle))appState.bottles.push(l.bottle);event(l,`Pre-raclage: ${l.prePieces.toLocaleString('it-IT')} flaconi mancanti`)}
 else if(type==='take-pre'){l.assignedTo=actor();l.stage='progress';event(l,'Pre-raclage preso in carico')}
 else if(type==='take-extra'){if(l.extraAssignedTo)throw Error('Big bag già preso in carico');l.extraAssignedTo=actor();event(l,'Big bag aggiuntivo preso in carico')}
 else if(type==='extra-loaded'){if(l.extraAssignedTo!==actor()&&!isAdmin())throw Error('Solo chi lo ha preso in carico può confermarlo');l.extraLoaded=true;event(l,'Big bag aggiuntivo caricato')}
 else if(type==='submit-pre'){l.bag1=Number(x.bag1);l.bag2=Number(x.bag2);if(l.extraRequested&&!l.extraLoaded)throw Error('Il big bag aggiuntivo non risulta caricato');l.stage='waiting-raclage';event(l,`Disponibilità: ${l.bag1+l.bag2} big bag`)}
 else if(type==='call-raclage'){l.stage='raclage';l.assignedTo='';event(l,'Raclage chiamato')}
 else if(type==='take-raclage'){l.stage='progress';l.assignedTo=actor();l.remainingPieces=-1;event(l,'Verifica raclage presa in carico')}
 else if(type==='submit-raclage'){l.remainingPieces=Math.max(0,Number(x.remainingPieces||0));l.stage='waiting-ct';event(l,`${l.remainingPieces.toLocaleString('it-IT')} pezzi avanzati`)}
 else if(type==='ct-decision'){l.ctDecision=x.decision;l.stage=x.decision==='ok'?'raclage-ok':'raclage';event(l,`Risposta CT: ${x.decision==='ok'?'OK':'Non OK'}`)}
 else if(type==='start-unload'){l.stage='unload';l.assignedTo=actor();event(l,'Scarico linea in corso')}
 else if(type==='confirm-clean'){l.cleanConfirmed=true;l.stage='finished';event(l,'Linea completamente pulita')}
 else if(type==='next-load'){l.nextBottle=x.nextBottle.trim();if(!l.nextBottle)throw Error('Inserisci il codice successivo');l.bottle=l.nextBottle;l.color=appState.bottleColors[l.nextBottle]||'';l.stage='progress';l.cleanConfirmed=false;l.remainingPieces=null;event(l,`Inizio carico codice ${l.nextBottle}`)}
 else if(type==='reset'){const activity=l.activity;appState.lines[selected]=freshLine(selected);appState.lines[selected].activity=activity;event(appState.lines[selected],'Linea riportata a riposo')}
 await save();render()
 }catch(e){toast(e.message,true)}}
function lists(){return `<datalist id="bottles">${appState.bottles.map(x=>`<option value="${esc(x)}">`).join('')}</datalist>`}
function colorManager(){if(!isCT())return'';return `<div class="notice"><strong>Codici flacone e colori</strong><div class="grid" style="margin-top:10px"><label class="field">Codice<input id="mapBottle" list="bottles"></label><label class="field">Colore<input id="mapColor" placeholder="Es. Blu"></label></div>${lists()}<div class="actions"><button id="saveColor">Crea o modifica associazione</button></div></div>`}
function panel(l){const undo=l.stage!=='idle'&&l.undo?'<button style="float:right" onclick="if(confirm(\'Annullare davvero l’ultima azione?\'))act(\'undo\')">Annulla ultima azione</button>':'',modes=isCT()?`<div class="actions"><label class="field">Correggi modalità linea<select onchange="act('set-stage',{stage:this.value})"><option value="${l.stage}">${esc(labels[l.stage])}</option><option value="progress">In corso · verde</option><option value="pre">Pre-raclage · arancione</option><option value="raclage">Raclage · giallo</option><option value="unload">Scarico · blu</option><option value="finished">Finito · rosso</option></select></label></div>`:'';const h=`<h2>Linea ${l.name}</h2><span class="status">${esc(labels[l.stage])}</span>${undo}${modes}`,info=`<div class="notice"><strong>Colore: ${esc(l.color||'—')}</strong> · Codice ${esc(l.bottle||'—')}<br>${Number(l.prePieces).toLocaleString('it-IT')} flaconi mancanti${l.extraRequested?' · 1 big bag aggiuntivo':''}</div>`;
 if(l.stage==='idle')return h+colorManager()+(isCT()?`<div class="grid"><label class="field">Codice flacone<input id="bottle" list="bottles"></label><label class="field">Pre-raclage · flaconi mancanti<input id="prePieces" type="number" min="0" value="10000"></label><label class="field">Big bag aggiuntivo<select id="extra"><option value="no">No</option><option value="yes">Sì</option></select></label></div>${lists()}<div class="actions"><button class="primary" id="savePre">Crea pre-raclage</button></div>`:'<p>In attesa che il CT crei un pre-raclage.</p>');
 if(l.stage==='pre')return h+info+`<div class="actions"><button class="primary" id="takePre">Prendo in carico</button></div>`;
 if(l.stage==='progress'&&l.remainingPieces===null){const extra=l.extraRequested?(!l.extraAssignedTo?'<button id="takeExtra">Prendo in carico big bag aggiuntivo</button>':`<p>Big bag aggiuntivo in carico a <strong>${esc(l.extraAssignedTo)}</strong>${l.extraLoaded?' · caricato':''}</p>${!l.extraLoaded&&(l.extraAssignedTo===actor()||isAdmin())?'<button id="extraLoaded">Conferma big bag caricato</button>':''}`):'';return h+info+`<p>Pre-raclage in carico a <strong>${esc(l.assignedTo)}</strong></p>${extra}<div class="grid"><label class="field">Big bag 1<select id="bag1"><option value="1">Pieno</option><option value="0">Vuoto</option></select></label><label class="field">Big bag 2<select id="bag2"><option value="1">Pieno</option><option value="0">Vuoto</option></select></label></div><div class="actions"><button class="primary" id="submitPre">Invia risposta</button></div>`}
 if(l.stage==='waiting-raclage')return h+info+(isCT()?'<div class="actions"><button class="primary" id="callRaclage">Chiama raclage</button></div>':'<p>In attesa della chiamata raclage del CT.</p>');
 if(l.stage==='raclage')return h+info+'<p>Serve la verifica dei pezzi avanzati.</p><button class="primary" id="takeRaclage">Prendo in carico la verifica</button>';
 if(l.stage==='progress'&&l.remainingPieces===-1)return h+info+`<p>Verifica in carico a <strong>${esc(l.assignedTo)}</strong></p><label class="field">Pezzi avanzati<input id="remaining" type="number" min="0"></label><div class="actions"><button class="primary" id="submitRaclage">Invia al CT</button></div>`;
 if(l.stage==='waiting-ct')return h+info+`<div class="notice"><strong>${Number(l.remainingPieces).toLocaleString('it-IT')} pezzi avanzati</strong><br>In attesa del CT.</div>${isCT()?'<div class="actions"><button class="primary" id="ctOk">CT: OK</button><button id="ctNo">CT: Non OK</button></div>':''}`;
 if(l.stage==='raclage-ok')return h+info+'<p>Raclage approvato.</p><button class="primary" id="startUnload">Avvia scarico linea</button>';
 if(l.stage==='unload')return h+info+'<p><strong>Scarico linea in corso.</strong></p><label><input id="cleanCheck" type="checkbox"> Linea completamente pulita</label><div class="actions"><button class="primary" id="confirmClean">Conferma linea pulita</button></div>';
 if(l.stage==='finished')return h+info+`<p><strong>Linea pulita confermata.</strong></p><label class="field">Codice successivo<input id="nextBottle" list="bottles"></label>${lists()}<div class="actions"><button class="primary" id="nextLoad">Conferma inizio carico</button><button class="danger" id="reset">Chiudi ciclo</button></div>`;
 return h+info+'<p>Carico in corso.</p><button class="danger" id="reset">Nuovo ciclo</button>'}
function bind(){const on=(id,fn)=>{const e=$('#'+id);if(e)e.onclick=fn};on('saveColor',async()=>{const b=$('#mapBottle').value.trim(),c=$('#mapColor').value.trim();if(!b||!c)return toast('Inserisci codice e colore',true);appState.bottleColors[b]=c;if(!appState.bottles.includes(b))appState.bottles.push(b);await save();render();toast('Associazione salvata')});on('savePre',()=>act('save-pre',{bottle:$('#bottle').value,prePieces:$('#prePieces').value,extraRequested:$('#extra').value==='yes'}));on('takePre',()=>act('take-pre'));on('takeExtra',()=>act('take-extra'));on('extraLoaded',()=>act('extra-loaded'));on('submitPre',()=>act('submit-pre',{bag1:$('#bag1').value,bag2:$('#bag2').value}));on('callRaclage',()=>act('call-raclage'));on('takeRaclage',()=>act('take-raclage'));on('submitRaclage',()=>act('submit-raclage',{remainingPieces:$('#remaining').value}));on('ctOk',()=>act('ct-decision',{decision:'ok'}));on('ctNo',()=>act('ct-decision',{decision:'no'}));on('startUnload',()=>act('start-unload'));on('confirmClean',()=>$('#cleanCheck').checked?act('confirm-clean'):toast('Conferma la verifica della linea',true));on('nextLoad',()=>act('next-load',{nextBottle:$('#nextBottle').value}));on('reset',()=>act('reset'))}
function render(){if(profile?.status!=='approved')return accessScreen();$('#access').innerHTML='';$('#app').hidden=false;$('#identity').innerHTML=`<span><strong>${esc(actor())}</strong><br><small>${profile.role==='admin'?'Amministratore':profile.role==='ct'?'CT':'Operatore'}</small></span><button id="logout">Esci</button>`;$('#logout').onclick=signOut;$('#lines').innerHTML=Object.values(appState.lines).map(l=>`<button class="line ${cls(l.stage)} ${l.name===selected?'selected':''}" data-line="${l.name}"><strong>${l.name}</strong><small>${esc(labels[l.stage])}</small></button>`).join('');document.querySelectorAll('.line').forEach(b=>b.onclick=()=>{selected=b.dataset.line;render()});const l=appState.lines[selected];$('#panel').innerHTML=panel(l);bind();$('#activity').innerHTML=l.activity.length?l.activity.map(e=>`<div class="event"><strong>${esc(e.text)}</strong><small>${esc(e.actor)} · ${showTime(e.at)}</small></div>`).join(''):'<p class="muted">Nessuna attività.</p>';if(isAdmin())renderAdmin()}
async function renderAdmin(){let box=$('#adminPanel');if(!box){box=document.createElement('section');box.id='adminPanel';box.className='admin';document.body.insertBefore(box,$('#app'))}const {data,error}=await db.from('profiles').select('*').order('created_at');if(error)return;box.innerHTML='<h2>Gestione accessi</h2><p>Approva, assegna il ruolo o blocca un utente.</p>'+data.map(u=>`<div class="user-row"><div><strong>${esc(u.display_name||'Senza nome')}</strong><small>${esc(u.email)}</small></div><select data-role="${u.id}" ${u.role==='admin'?'disabled':''}><option value="operator" ${u.role==='operator'?'selected':''}>Operatore</option><option value="ct" ${u.role==='ct'?'selected':''}>CT</option><option value="admin" ${u.role==='admin'?'selected':''}>Amministratore</option></select><span class="badge">${u.status}</span>${u.role==='admin'?'':`<button data-status="${u.id}" data-next="${u.status==='approved'?'blocked':'approved'}">${u.status==='approved'?'Blocca':'Approva'}</button>`}</div>`).join('');box.querySelectorAll('[data-role]').forEach(e=>e.onchange=()=>updateUser(e.dataset.role,{role:e.value}));box.querySelectorAll('[data-status]').forEach(e=>e.onclick=()=>updateUser(e.dataset.status,{status:e.dataset.next}))}
async function updateUser(id,change){const {error}=await db.from('profiles').update(change).eq('id',id);if(error)return toast(error.message,true);toast('Utente aggiornato');renderAdmin()}
async function boot(){const {data}=await db.auth.getSession();session=data.session;if(session){try{profile=await getProfile()}catch(e){toast('Profilo non disponibile',true)}}if(profile?.status==='approved'){render();await loadRemote()}else accessScreen();db.auth.onAuthStateChange(async(_,s)=>{session=s;if(s){profile=await getProfile();if(profile.status==='approved'){render();loadRemote()}else accessScreen()}})}
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});boot();setInterval(async()=>{if(session){try{const p=await getProfile();if(p.status!==profile?.status||p.role!==profile?.role){profile=p;render()}}catch{}}loadRemote()},2500);
